parameters:
 silex.controller_resolver.class: Kagux\SilexIntegrationBundle\HttpKernel\ControllerResolver
 silex.routes.loader.class: Kagux\SilexIntegrationBundle\Router\Loader\SilexLoader
 silex.app.class: Silex\Application
 silex.route.converter.class: Kagux\SilexIntegrationBundle\Silex\Route\Converter
 silex.integration.twig.form.resources.resolver.class: Kagux\SilexIntegrationBundle\Twig\Form\Engine\Resources\Resolver
 silex.middleware.listener.class: Silex\EventListener\MiddlewareListener
 silex.string_to_response.listener.class: Silex\EventListener\StringToResponseListener
 silex.integration.service.pool.class: Kagux\SilexIntegrationBundle\Silex\Integration\Service\Pool\ServicePool


services:

 silex.app:
    class: %silex.app.class%

 silex.controller_resolver:
    class: %silex.controller_resolver.class%
    arguments: [@original.controller_resolver, @silex.app]

 silex.routes.loader:
    class:  %silex.routes.loader.class%
    arguments: [@silex.app]
    tags:
     - { name: routing.loader, priority: -10 }

 silex.route.converter:
    class: %silex.route.converter.class%
    arguments: [@silex.app, @request]
    scope: request
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: convert, priority: -10}

 silex.middleware.event.listener:
     class: %silex.middleware.listener.class%
     arguments: [@silex.app]
     tags:
       - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -1024}
       - { name: kernel.event_listener, event: kernel.reponse, method: onKernelResponse, priority: 128}

 silex.string_to_response.listener:
     class: %silex.string_to_response.listener.class%
     tags:
       - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: -10}

 silex.integration.twig.form.resources.resolver:
    class: %silex.integration.twig.form.resources.resolver.class%
    arguments: [@silex.app, %twig.form.resources%]

 silex.integration.twig.form.resources:
    class: array
    factory_service: silex.integration.twig.form.resources.resolver
    factory_method: resolve

 silex.doctrine.orm.default_metadata_driver.factory:
    class: Kagux\SilexIntegrationBundle\Doctrine\Metadata\DriverFactory
    arguments: [@silex.app, @original.doctrine.orm.default_metadata_driver]

 silex.doctrine.orm.default_metadata_driver:
    class: Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain
    factory_service: silex.doctrine.orm.default_metadata_driver.factory
    factory_method: create

 silex.integration.service.pool:
    class: %silex.integration.service.pool.class%
    calls:
      - [setSilex, [@silex.app] ]


