parameters:
 silex.controller_resolver.class: Kagux\SilexIntegrationBundle\HttpKernel\ControllerResolver
 silex.routes.loader.class: Kagux\SilexIntegrationBundle\Router\Loader\SilexLoader
 silex.app.class: Silex\Application
 silex.app.integrator.class: Kagux\SilexIntegrationBundle\Silex\ApplicationIntegrator
 silex.route.converter.class: Kagux\SilexIntegrationBundle\Silex\Route\Converter
 silex.integration.twig.form.resources.resolver.class: Kagux\SilexIntegrationBundle\Twig\Form\Engine\Resources\Resolver

services:

 silex.app:
    class: %silex.app.class%

 silex.app.integrator:
    class: %silex.app.integrator.class%
    arguments: [@service_container, @silex.app]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: integrate, priority: 31}

 silex.controller_resolver:
    class: %silex.controller_resolver.class%
    arguments: [@original.controller_resolver, @silex.app]

 silex.routes.loader:
    class:  %silex.routes.loader.class%
    arguments: [@silex.app]
    tags:
     - { name: routing.loader, priority: -10 }

 silex.route.converter:
    class: %silex.route.converter.class%
    arguments: [@silex.app, @request]
    scope: request
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: convert, priority: -10}

 silex.integration.twig.form.resources.resolver:
    class: %silex.integration.twig.form.resources.resolver.class%
    arguments: [@silex.app, %twig.form.resources%]

 silex.integration.twig.form.resources:
    class: array
    factory_service: silex.integration.twig.form.resources.resolver
    factory_method: resolve